// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_travel_1000 = "CgkI7-2Us6EDEAIQBg"; // <GPGSID>
        public const string achievement_travel_50m = "CgkI7-2Us6EDEAIQAg"; // <GPGSID>
        public const string achievement_travel_300m = "CgkI7-2Us6EDEAIQBA"; // <GPGSID>
        public const string achievement_travel_150m = "CgkI7-2Us6EDEAIQAw"; // <GPGSID>
        public const string achievement_travel_500m = "CgkI7-2Us6EDEAIQBQ"; // <GPGSID>
        public const string leaderboard_highscores = "CgkI7-2Us6EDEAIQAQ"; // <GPGSID>

}

